### ISSUE TITLE
FRITZ!Box 7530 UnauthorizedERR_NONEWebserver

### ISSUE THREAD

**Issue by Pivert** [pdreker/fritzbox_exporter#12]
Hi,

Currently, having an issue with the script, and the error is not really helping:

First a quick description of the environment & libs:
```
root@prometheus:/opt/fritzbox_exporter# pip3 install prometheus-client
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.8/dist-packages (0.9.0)
root@prometheus:/opt/fritzbox_exporter# pip3 install fritzconnection
Requirement already satisfied: fritzconnection in /usr/local/lib/python3.8/dist-packages (1.4.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from fritzconnection) (2.22.0)
root@prometheus:/opt/fritzbox_exporter# python --version
Python 3.8.5
root@prometheus:/opt/fritzbox_exporter# env | grep FRITZ | grep -v PASS
FRITZ_HOST=192.168.178.1
FRITZ_USER=monitoring
```

I can log-in with the monitoring user from "home network".

When I execute the script:
```
root@prometheus:/opt/fritzbox_exporter# python fritzbox_exporter.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 123, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fritzbox_exporter.py", line 123, in <module>
    REGISTRY.register(FritzBoxCollector(os.getenv('FRITZ_HOST', 'fritz.box'), os.getenv('FRITZ_USER'), os.getenv('FRITZ_PASS')))
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "fritzbox_exporter.py", line 31, in collect
    info_result = self.conn.call_action('DeviceInfo:1', 'GetInfo')
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/fritzconnection.py", line 227, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 238, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 222, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 133, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Sat, 30 Jan 2021 16:35:30 GMT

```

Just checking the lib from the REPL:

```
root@prometheus:/opt/fritzbox_exporter# python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fritzconnection import FritzConnection
>>> 
>>> fc = FritzConnection(address='192.168.178.1')
>>> fc.reconnect()  # get a new external ip from the provider
>>> print(fc)  # print router model informations
FRITZ!Box 7530 at http://192.168.178.1
FRITZ!OS: 7.13
>>> quit()
root@prometheus:/opt/fritzbox_exporter# 
```

**Comment by pdreker** [comment]
Normally that's what happens, if the login did not succeed, as you already hinted at.

I'm speculating here, but any "funny" characters in the password? If so, could you try "pure" alphanumerical, just to see, if that's it?

Also the example from the REPL does not explicitly use authentication (unless, you have the appropriate environment vars set, which are different from the the exporter.

Could you try logging in directly from the python shell:
```python
fc = FritzConnection(address='192.168.178.1', user='monitoring', password='YOUR_PASSWORD')
```

Also: i've been "shoving" the code around a bit today, depending on when you downloaded it, I might have broken something. I'll check that on my end, but the actual exporter should not have taken a hit...

**Comment by Pivert** [comment]
Thanks Patrick,

The password is exclusively alphanumeric. To compensate it's longer...

```
In [4]: len(password)                                                                                                                                                                                             
Out[4]: 32

In [5]: from fritzconnection import FritzConnection                                                                                                                                                               

In [6]: fc = FritzConnection(address='192.168.178.1', user='monitoring', password=password)                                                                                                                       

In [7]: fc.modelname                                                                                                                                                                                              
Out[7]: 'FRITZ!Box 7530'

```

**Comment by pdreker** [comment]
Could you try downgrading fritzconnection to 1.2.1 (before 1.3.0, to be precise)?

I have a hunch, that this might be connected to https://github.com/kbr/fritzconnection/issues/82 (Older FritzOS Version... you are running 7.13, while 7.21 is current).

Checking on my end the current master branch works for me in docker as well as native on my Macbook against my 7590 with 7.21.

**Comment by pdreker** [comment]
> I have a hunch, that this might be connected to [kbr/fritzconnection#82](https://github.com/kbr/fritzconnection/issues/82) (Older FritzOS Version... you are running 7.13, while 7.21 is current).
I'll state the obvious, just for completeness: upgrading Fritz!OS may also be an option... But I won't be the guy saying "Upgrade, closed" ;-)

**Comment by pdreker** [comment]
I found another vector: Could you please check that under "network settings" (My Fritz!Box runs german locale... There it is under "Heimnetz" (Home Network?) -> Netzwerk (Network) -> Netzwerkeinstellung (Tab at the top - network settings)) you have enabled "access for applications" and "statusinformation using UPnP"? To my understanding "access for applications" should be enough, but both are mentioned in the context of fritzconnection.

**Comment by Pivert** [comment]
Thanks Patrick,

Those are default options (that I did not changed):
![image](https://user-images.githubusercontent.com/7798433/106365842-79571280-6338-11eb-8f23-c97f5f1e72c9.png)

I'll check for upgrading the Fritz!Box first. But when I checked this afternoon it just shows it's up to date and there's no higher version... I'll check again.

**Comment by pdreker** [comment]
Check https://avm.de/nc/service/downloads/productsupport//fritzbox-7530/, that where I have the information, that 7.21 is available for the 7530.

No guarantees though.

Please report back.

**Comment by pdreker** [comment]
Here's another one to test:
Go into python shell und try the following sequence using fritzconnection:
```python
from fritzconnection import FritzConnection
fc = FritzConnection(address='192.168.178.1', user='monitoring', password=password)
fc.call_action('DeviceInfo:1', 'GetInfo')
```
This should return a dictionary containing basic information about the FritzBox (model name, serial, software version, uptime). The reasoning behind this is that this is the exact call in the exporter, which triggers the error and is actually the first communication the exporters makes with the box.

I still find it interesting, that the fritzconnection module seems to work but then the first basic call to the box fails with "401 Unauthorized". I have also checked the AVM documentation, and the error can mean several things, only one of which actually is "Unauthorized". In the "call_action context it can also mean that the action called is unknown or obsolete.

TR064 normally requires some kind of "discovery" and the exporter (currently) just blindly uses whatever my 7490/7590 returned to test calls.

Could you maybe simply do a `curl 192.168.178.1:49000/tr64desc.xml` and put the resulting XML up somewhere and link it here? This basically contains a description of protocol information and what services are actually available on your box.

**Comment by Pivert** [comment]
Thanks Patrick,
So, upgrade seems not available. Maybe only in Germany ?
And downgrade to
```
pip3 install fritzconnection==1.2.1
```

But shortening the password to 12 characters did help !
The script starts without error, and is working:
```
root@prometheus:/opt/fritzbox_exporter# lsof -Pni | grep python.*LISTEN
python    31763            root    4u  IPv4 29204367      0t0  TCP *:9787 (LISTEN)
root@prometheus:/opt/fritzbox_exporter# curl http://localhost:9787/metrics
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 98.0
python_gc_objects_collected_total{generation="1"} 291.0
python_gc_objects_collected_total{generation="2"} 0.0
```

Thanks for you help !

P.S.: I updated to the current version (fritzconnection==1.4.0) and it works as well. So, definitely a password problem.

**Comment by Pivert** [comment]
Closed
