### ISSUE TITLE
Byterate

### ISSUE THREAD

**Issue by ojwer** [pdreker/fritzbox_exporter#35]
Metrics which are not yet scraped by this exporter (as far as I have seen):
1. FritzBox DSL 7590 V7.25
2. Servicename: WANCommonInterfaceConfig1 Action: GetAddonInfos
3. Sorry, the Helper didn't run properly. Fields are "NewByteReceiveRate" and "NewByteSendRate".
4. At the moment I am getting this info in an nodered environment (node-red-contrib-fritz) from the Fritzbox and I would like to migrate to Fritzbox_exporter.

**Comment by pdreker** [comment]
Seems like I'll have to bump my box to 7.25 tonight and I'll have a look.

**Comment by pdreker** [comment]
Interestingly I only get "GetAddonInfos" under the service "WANCommonIFC1"... I would have assumed, that this is just a shortcut to WANCommonInterfaceConfig1, but oh well...

**Comment by ojwer** [comment]
I am not sure, wether this action is from the TR-064 or the UPnP/IGD API. That would perhaps explain the difference.

**Comment by pdreker** [comment]
Doesn't matter - I have just merged current develop into master triggering the 1.0.5 release, which has the metrics as "fritz_wan_datarate". The action is currently building the images, they should be available shortly.

Just a suggestion: It might be more elegant to actually use PromQL to get the datarate of the WAN interface, as this offers more control about what values are used. The API counters only show the data rate *at that moment*. So if you are scraping every 60s you may actually miss traffic, if there is a huge transfer which started after the last scrape and terminates before the next scrape.

So a query for Grafana like

```
rate(fritz_wan_data_bytes_total{direction="down"}[10m])
```

will actually produce the real bytes per second over the last 10m.
