### ISSUE TITLE
Docker-Container throws "Fatal Python error" on HypriotOS/armv7

### ISSUE THREAD

**Issue by monsdar** [pdreker/fritzbox_exporter#38]
_Disclaimer: This is kind of a self-post to help others with the same issue in the future._

I'm running Prometheus, Grafana and a bunch of exporters on a Raspberry Pi 4 in Docker containers. I'm using Hypriot OS for that. When calling `docker run -d -e FRITZ_EXPORTER_CONFIG="192.168.178.1,username,password" -p 9787:9787 --name fritz_exporter pdreker/fritz_exporter` it fails with during startup with the following message: `Fatal Python error: init_interp_main: can't initialize time`.

I was able to work around that by starting in priviliged mode with `docker run ... --privileged ...`, but this is not working for `docker build ...` for example.

**Comment by monsdar** [comment]
Within [this StackOverflow question](https://askubuntu.com/questions/1263284/apt-update-throws-signature-error-in-ubuntu-20-04-container-on-arm) they mention something similar and that the cause of this issue is an old version of `libseccomp2` on ARM computers.

In the end I was able to download [libseccomp2_2.5.1-1_armhf.deb](https://packages.debian.org/sid/armhf/libseccomp2/download) from the Debian repositories which installed using `sudo dpkg -i libseccomp2_2.4.3-1+b1_armhf.deb` without any issues. After that I could run and build the docker image without any issues.

Hope this helps someone else as well.

**Comment by pdreker** [comment]
After you mentioned this I remembered that I had to do the exact same here (for another container, but also on a Raspi4 with "standard" RaspianOS.

I'll document this in the README.
